name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?color_snake=3c7dd9&color_dots=4b91f1,64a1f4&color_head=ff6b00&head_radius=8&growth_factor=1.1
            dist/snake-dark.svg?palette=github-dark&color_snake=64a1f4&color_dots=8dbdff,bfd6f6&color_head=ff8c00&head_radius=8&growth_factor=1.1&color_bg=0d1117
          # Animation settings
          frame_duration: 60
          frames_per_day: 8
          snake_speed: 1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update animated snake [skip ci]"